apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: cluster-viewonly
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'view'
  - 'list'
  - 'get'
- nonResourceURLs:
  - '*'
  verbs:
  - 'view'
  - 'list'
  - 'get'
